version: '3.3'
services:

  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:8888:8888"
    depends_on:
      - db

volumes:
  mysql-data:
